name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  get_it: ^7.6.0
  injectable: ^2.2.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0

  shared:
    path: ../shared

dev_dependencies:
  lints: ^2.0.0
  flutter_lints: ^2.0.3
  test: ^1.21.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.0
