name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  get_it: ^7.2.0
  injectable: ^2.2.0
  async: ^2.11.0
  package_info_plus: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.0
